export default {
  LOGIN: 'LOGIN',
  FORGET_PASSWORD: 'FORGET_PASSWORD',
  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  APP_DATA: 'APP_DATA',
  NO_INTERNET: "NO_INTERNET",
  UPDATE_LOC:'UPDATE_LOC',
  ADD:"ADD",
  DELETE:"DELETE",
  UPDATE:'UPDATE',
  ITEMINCREMENT:"ITEMINCREMENT",
  ITEMDECREMENT:"ITEMDECREMENT",
  INITIALPRICE:"INITIALPRICE",
  LOGOUT:"LOGOUT"
};